# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.6"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.name = "cis"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.hostname = "server1"
  config.vm.network :private_network, ip: "192.168.33.7"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "cis-rhel-ansible/playbook.yml"
    ansible.sudo = true
  end

end
