# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "thussain/openshift"
  config.ssh.insert_key = false

config.push.define "atlas" do |push|
  push.app = "thussain/rhel7.1"
end
  config.vm.provider "virtualbox" do |v|
    v.name = "openshift"
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.hostname = "ose3-master"
  config.vm.network :private_network, ip: "192.168.33.100"

  config.vm.hostname = "ose3-node1"
  config.vm.network :private_network, ip: "192.168.33.101"

  config.vm.hostname = "ose3-node2"
  config.vm.network :private_network, ip: "192.168.33.102"

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "cis-rhel-ansible/playbook.yml"
  #  ansible.sudo = true
  #end

end
